#########################################################################
# ⭐⭐⭐  Set parameters carefully for satisfied performance!   ⭐⭐⭐ #
#########################################################################

mass        : 0.319 # kg 
gra         : 9.81 
pose_solver : 3     # 0:From ZhepeiWang (drag & less singular) 1:From ZhepeiWang, 2:From rotor-drag    
ctrl_freq_max   : 100.0
use_bodyrate_ctrl: true 
max_manual_vel: 2.0
max_angle: 40  # Attitude angle limit in degree. A negative value means no limit.
low_voltage: 13.2 # 4S battery
max_thr: 12 #max12.3
min_thr: 2.5 #min 2.5

rc_reverse: # *
    roll: false
    pitch: false
    yaw: false
    throttle: true

auto_takeoff_land:
    enable: true
    enable_auto_arm: true
    no_RC: true
    takeoff_height: 1.0 # m
    takeoff_land_speed: 0.2 # m/s

thrust_model: # The model that maps thrust signal u(0~1) to real thrust force F(Unit:N): F=K1*Voltage^K2*(K3*u^2+(1-K3)*u). 
    print_value: false # display the value of “thr_scale_compensate” or “hover_percentage” during thrust model estimating.
    accurate_thrust_model: false  # This can always enabled if don't require accurate control performance :-)
    # accurate thrust mapping parameters
    K1: 0.7583 # Needs precise calibration!
    K2: 1.6942 # Needs precise calibration!
    K3: 0.6786 # Needs precise calibration! K3 equals THR_MDL_FAC in https://docs.px4.io/master/en/config_mc/pid_tuning_guide_multicopter.html.
    # approximate thrust mapping parameters
    # hover_percentage: 0.197  # Thrust percentage in Stabilize/Arco mode # *
    hover_percentage: 0.406  # Thrust percentage in Stabilize/Arco mode # *

gain: 
    # Cascade PID controller. Recommend to read the code.
    # Kp0: 5.5
    # Kp1: 5.5
    # Kp2: 5.5
    # Kv0: 5.5
    # Kv1: 5.5
    # Kv2: 5.5  非SO(3)模式参数，默认质量1kg

    Kp0: 13.320    # kp_x
    Kp1: 13.755    # kp_y
    Kp2: 13.889   # kp_z
    Kv0: 3.478    # kd_x → 速度环P(阻尼)
    Kv1: 2.902    # kd_y
    Kv2: 3.359    # kd_z
       # ↓↓↓ No use now --
    Kvi0: 0.336   # ki_x → 积分
    Kvi1: 0.274   # ki_y
    Kvi2: 0.224   # ki_z
    Kvd0: 0.0
    Kvd1: 0.0
    Kvd2: 0.0
    # ↓↓↓ Only used in rate control mode.
    KAngR: 12.00
    KAngP: 12.00
    KAngY: 12.0

    maxRateR: 8.0
    maxRateP: 8.0
    maxRateY: 8.0
    # KAngR: 1.0
    # KAngP: 1.0
    # KAngY: 1.0
rotor_drag:  
    x: 0.0  # The reduced acceleration on each axis caused by rotor drag. Unit:(m*s^-2)/(m*s^-1).
    y: 0.0  # Same as above
    z: 0.0  # Same as above
    k_thrust_horz: 0.0 # Set to 0 recommended... --

msg_timeout:
    odom: 0.5
    rc:   0.5
    cmd:  0.5
    imu:  0.5
    bat:  0.5
